### ISSUE TITLE
bad return from https://api.pirateweather.net

### ISSUE THREAD

**Issue by Valley8140** [Pirate-Weather/pirateweather#103]
I am kind of stuck on these messages;
`  
  
  
  
  
  
  `
  
I'm using the API in a script I got from Saratoga Weather on a website done in Wordpress on a 3rd party hosting provider, I can use curl on the command line so it seems that isn't blocked.

**Comment by cloneofghosts** [comment]
I know it's been a while since this issue was opened but did you ever solve this issue or are you still having problems?

**Comment by cloneofghosts** [comment]
I haven't seen a response from you @Valley8140 so I'm going to close this for now. If you're still having issues then feel free to re-open this issue.
