### ISSUE TITLE
API Returning Incorrect TimeZone

### ISSUE THREAD

**Issue by radekbocon** [Pirate-Weather/pirateweather#104]
Hello, I found a bug where timezone and offset are wrong for some locations in the Netherlands.
As example here is Amsterdam:
**Actual:**
timezone: "Etc/GMT" 
offset: 0
**Expected:**
timezone: "CEST" 
offset: 2

![image](https://github.com/alexander0042/pirateweather/assets/86799925/b9d11789-e750-4508-8588-0cbc76afd94a)

Utrecht on the other hand shows correct values:
![image](https://github.com/alexander0042/pirateweather/assets/86799925/25234d35-be8f-4984-9117-7ec2529ceae9)

**Comment by cloneofghosts** [comment]
Seems like the rapid timezone used isn't returning the correct timezone for your location. If you include tz=precise in the URL the API returns the correct timezone for your location while adding a bit of latency.

While that will solve your issue I feel like the [TimeZoneFinder](https://timezonefinder.readthedocs.io/en/latest/) should be used by default as I've noticed the rapid timezone finder seems to have it's issues in various locations (St. John's, Newfoundland and Tampa, FL are places I've noticed it be incorrect)

**Comment by radekbocon** [comment]
Thanks, that solved my issue

**Comment by cloneofghosts** [comment]
Glad to be able to help solve the issue. I'll mention @alexander0042 to see if there's anything he can do to solve the issue with the rapid timezone algorithm so you don't have to use the precise one.

**Comment by alexander0042** [comment]
Thanks for tagging me! @cloneofghosts is correct (as per usual), the tz=precise flag will fix things for now. It's a bit of a balancing act, since it adds about 0.05 s to use the more precise approach, which isn't awful, but most people don't need the exact time zone, so also doesn't matter too much. I'm hoping to significantly reduce the data access time in the next version, which might give enough overhead to re-enable this for everyone

**Comment by cloneofghosts** [comment]
Just popping in to say that this issue has been fixed on the current development version of the V2 API which should hopefully be out sometime this winter.

**Comment by alexander0042** [comment]
Great call here, thanks for closing!
