### ISSUE TITLE
Unable to request re-send of timed-out verification email

### ISSUE THREAD

**Issue by rce1086** [Pirate-Weather/pirateweather#120]
### Describe the issue

Hi,
 due to my being too slow to respond to the time limited verification email, I cannot progress with trying to request an API key: it keeps saying “verification email sent”, but this is a time limited mail - it has timed out, but I see no way to request a new one to be sent out….
![IMG_0082](https://github.com/Pirate-Weather/pirateweather/assets/8218359/c2b5bf2a-6888-482b-aa90-565f3a1d2081)

### Acknowledgements

- [X] I have searched this repository to see if the issue has already been reported.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
I've assigned this to @alexander0042 so he can take a look whenever he gets a chance. If you try signing up for the API with the same email do you get an error message or does it allow you to register again?

If it still prevents you from registering with the same email a workaround you can use is to add + then a string and it will be treated as a different email. For example if your email was example@gmail.com you can use example+pw@gmail.com and it should allow you to register again as a new account.

**Comment by rce1086** [comment]
Trying to sign up for a key with the same email just leads to the page shown above, but I will try from a different browser, to eliminate any chance of cached data issues…
So, different browser, but same login makes no difference, back to the page above: no error, just this same page…

I’ll try the work-around…

Thanks

**Comment by rce1086** [comment]
Thanks, the updated page, with the send button, has fixed the issue.

Thanks very much for this, guys.

**Comment by alexander0042** [comment]
Went looking for this issue and was briefly very confused why I couldn't find it. Super grateful for @cloneofghosts for jumping in to help here!
