### ISSUE TITLE
502 error when fetching forecast for Luxembourg 15 December 8am

### ISSUE THREAD

**Issue by harristom** [Pirate-Weather/pirateweather#122]
### Describe the bug

https://api.pirateweather.net/forecast/{key}/49.606302,6.13625,1702627200?units=ca

This returns a 502:
```
{
    "message": "Bad Gateway",
    "error": "could not JSON decode Lambda function response: statusCode validation failed"
}
```

Is there a limit of how far ahead you can request a forecast? I couldn't see it in the docs.

Thanks :)

### Expected behavior

Get the weather forecast for the requested location and datetime

### Actual behavior

502 error

### API Endpoint

Production

### Location

Luxembourg, Luxembourg

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
@alexander0042 I double checked the API documentation and there is nothing there which states that requesting a date in the future causes an error. Might be a good idea to add something to the docs which says that requesting dates in the future will not work.

**Comment by alexander0042** [comment]
On top of this (for once). Done in commit https://github.com/Pirate-Weather/pirateweather/commit/9243213952ab10681325351d89421d772510ba4e
