### ISSUE TITLE
recieving "could not JSON decode Lambda function response: statusCode validation failed" error when using time machine

### ISSUE THREAD

**Issue by LingLing42** [Pirate-Weather/pirateweather#147]
Hello, 

I'm trying to get weather data for some (3) locations, but I get the same response:
`{
  "message": "Bad Gateway",
  "error": "could not JSON decode Lambda function response: statusCode validation failed"
}`

This issue begins with 2023-11-01 00:00:00 until today. I also tested it with creators example, still the same response(s).
example link: 

`https://timemachine.pirateweather.net/forecast/[API-key]/52.54781505900733,13.342027465679983,1698793200?lang=de&units=si`

_Originally posted by @LingLing42 in https://github.com/Pirate-Weather/pirateweather/issues/74#issuecomment-1919925404_

**Comment by cloneofghosts** [comment]
Did some quick testing and it seems like days up until October 31st work without issues. Not sure if it's something related to AWS removing the ERA-5 dataset (see https://github.com/Pirate-Weather/pirateweather/issues/130#issuecomment-1893752959) or something else.

Will ping @alexander0042 to take a look and see what's happening and to update the docs if things have changed.

**Comment by patel-jeel92** [comment]
Getting the same error message for the regular endpoint. 
https://api.pirateweather.net/forecast/<api_key>/<lat>,<long>?units=si&extend=hourly

**Comment by alexander0042** [comment]
As is custom, @cloneofghosts is exactly correct here. Since I switched over to Google, the latest data they make available is May 2023, so that's the latest at the moment. I've updated timemachine with a better error message, so appreciate you bringing this to my attention.

I have a meeting with AWS next week to see if we can work something out, but the wheels of bureaucracy turn slowly, so I think it might be a while before this gets fixed

**Comment by cloneofghosts** [comment]
> Since I switched over to Google, the latest data they make available is May 2023, so that's the latest at the moment.

During my quick testing yesterday I was getting data in October for my location. It could be that the Google page is outdated and you can get data after May?

I didn't use the TimeMachine on DarkSky much so I don't know if the TimeMachine was just saved forecast data or if it was a mix of both. I don't know if in error cases it would show the requested lat/long with timezone data and an error message? The translation module has messaging about things being unavailable but it could just be for the minutely forecasts.
