### ISSUE TITLE
Local Time format not working for time machine API

### ISSUE THREAD

**Issue by drmrbrewer** [Pirate-Weather/pirateweather#162]
### Describe the issue

As explained [in the docs](https://pirateweather.net/en/latest/API/#time_1), it should be possible to specify the date/time for the time machine API in the local time zone for the requested location.  The datestring should be in the form `[YYYY]-[MM]-[DD]T[HH]:[MM]:[SS]` i.e. without any `Z` at the end (which would signify UTC time format).

Example request:

https://timemachine.pirateweather.net/forecast/my_api_key/47.08,-123.01,2000-01-01T12:00:00?exclude=daily,alerts,flags&extend=hourly&units=si&lang=en

Response:

`"Invalid Time Specification"`

It is really convenient to be able to specify the date/time in local time, because typically I just want the data for a particular date, so I can specify noon on that date (as per example request above) and be sure that I'm getting the right data without having to think about time zones.

Thanks!

### Acknowledgements

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
I tested this for myself and can confirm that the datestring only works if you query it in UTC time. I'm going to ping @alexander0042 to sort out this issue for you.

**Comment by alexander0042** [comment]
Great catch here- it's in the docs, so it should work!

I put a fix in (variable was missing) and pushed it live, so let me know if this is working again for you

**Comment by cloneofghosts** [comment]
Haven't heard a response for issue for about a month and I can confirm that this issue is fixed. I'm going to close this issue now but feel free to re-open if it's still not working for you.
