### ISSUE TITLE
Getting error when i try to use the wether api - could not JSON decode Lambda function response: statusCode validation failed.

### ISSUE THREAD

**Issue by abbmytosa** [Pirate-Weather/pirateweather#194]
### Describe the bug

1. This works when the lat and long is given for Europe region.  But when we give lat and long for India region it was not working. Giving below error.
2. 
API:
https://timemachine.pirateweather.net/forecast/*********/15.34499,75.14537,1420223400?units=si
Error:

{
    "message": "Bad Gateway",
    "error": "could not JSON decode Lambda function response: statusCode validation failed"
}

### Expected behavior

Actual response

### Actual behavior

{
    "message": "Bad Gateway",
    "error": "could not JSON decode Lambda function response: statusCode validation failed"
}

### API Endpoint

TimeMachine

### Location

15.34499,75.14537

### Other details

https://timemachine.pirateweather.net/forecast/*********/15.34499,75.14537,1420223400?units=si

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
Good catch here, investigating now!

**Comment by alexander0042** [comment]
Ok, should be fixed now!

**Comment by abbmytosa** [comment]
Thanks for quick turnaround!!!. Tested in postman and api is working fine. We are also testing the application.
