### ISSUE TITLE
Internal Service Error

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#208]
### Describe the bug

The API has been returning an Internal Service Error message for my location. From my testing it seems to be only for those locations in the HRRR domain as it's still up for those locations outside of the domain.

If add HRRR to the excludes then the API returns data like normal confirming my suspicion that something with the HRRR model is causing the issue.

### Expected behavior

API should return data for the requested location

### Actual behavior

Internal Server Error message is shown instead

### API Endpoint

Production

### Location

Ottawa, Ontario

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by carlos-sarmiento** [comment]
I'm also getting a 500 error from Pirate Weather. Don't know what HRRR is, but this URL fails (api key redacted):
https://api.pirateweather.net/forecast/xxxxxxxxxxxx/29.73,-95.65?units=si&extend=hourly&version=2

**Comment by rayvd** [comment]
Same also.  Adding exclude=hrrr to the call seems to make things work.

**Comment by alexander0042** [comment]
I'm so sorry for this outage! I take uptime pretty seriously. so this is a big issue. What happened was a bug in my datetime rounding code failed because of the month rollover, and excluding HRRR fixed it since I don't have to round that one. It's back up and running now, and corrected so it won't happen again!

**Comment by cloneofghosts** [comment]
Can confirm everything is working again.

**Comment by iganeshk** [comment]
> I'm so sorry for this outage! I take uptime pretty seriously. so this is a big issue. What happened was a bug in my datetime rounding code failed because of the month rollover, and excluding HRRR fixed it since I don't have to round that one. It's back up and running now, and corrected so it won't happen again!

service seems to be erroring out currently with 500.
