### ISSUE TITLE
Getting a mix of versions

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#210]
### Describe the bug

When I query the API directly in the flags section sometimes I'm getting version 2.0.2 and sometimes I get 2.0.3. I think it's the same issue that I got during the beta where one of the servers didn't get restarted when the new version released?

### Expected behavior

Always getting version 2.0.3

### Actual behavior

Sometimes I get version 2.0.2 and sometimes I get 2.0.3

### API Endpoint

Production

### Location

Ottawa, Ontario

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
@alexander0042 Has this been fixed? I seem to be getting 2.0.3 everytime I check the flags section now.

**Comment by cloneofghosts** [comment]
@alexander0042 Seeing the same thing again with 2.0.4 and 2.0.5.

**Comment by alexander0042** [comment]
On it!

**Comment by cloneofghosts** [comment]
Did this get fixed? I haven't seen an update since your post ~2h ago.

**Comment by alexander0042** [comment]
Yup! Restarted both containers, so should be fixed now

**Comment by cloneofghosts** [comment]
Awesome, thanks! I'll re-open this issue if I see 2.0.4 pop up again.

**Comment by cloneofghosts** [comment]
@alexander0042 I seem to be getting a mix of V2.3.2 and V2.3.3 this morning/afternoon. The containers probably need a restart again.

**Comment by alexander0042** [comment]
Since this was a bit of a larger update, I wanted to give it some time to make sure everything would go smoothly... but then forgot about the other container. Restarted now, so should be live in ~20 minutes or so

**Comment by cloneofghosts** [comment]
Yup, is looking good now.
