### ISSUE TITLE
Finish and Update API Documentation

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#214]
### Describe the issue

I know this is second on the roadmap but I figure having an actual issue might be helpful as a reminder to you to finish it up.

- [x] Homepage Recent Updates section
- [x] API Docs - Make sure information is correct and up-to-date with V2
- [x] Home Assistant Documentation - https://github.com/Pirate-Weather/pirate-weather-ha/issues/146 and https://github.com/Pirate-Weather/pirate-weather-ha/issues/211
- [x] Changelog - Make sure information is correct
- [x] Update changelog for V2.0.4
- [x] OpenAPI Specification - Last updated for V1.4
- [x] Roadmap - Make sure information is correct
- [x] Document which models are used where in the currently block

### Documentation URL

https://pirateweather.net/en/latest/

### Acknowledgements

- [X] I have searched this repository to see if the issue has already been reported.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
Working on this now (for real this time). Started a new branch to track progress and see if I've got my formatting correct

**Comment by cloneofghosts** [comment]
I almost pinged you about this issue but it looks like I won't need to. I've created a draft PR which I've linked up to various different issues with the documentation tag in this repo and the HA repo.

**Comment by alexander0042** [comment]
Nice! Also wanted to say thank you for the first stab at the V2.0 docs. You got just about everything, and made my edits way easier
