### ISSUE TITLE
NBM data stopped integrating

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#224]
### Describe the bug

I noticed yesterday that the NBM model has stopped integrating with the last update being the 11Z on 2024-05-13. I know sometimes the data stops integrating for a few hours but then fixes itself. I checked this morning and I'm seeing the same time in the `sourceTimes` section so it appears something is broken.

I checked the status page that was linked in #191 and I see nothing for the NBM model so I suspect the issue is on PW's end? The NBM Fire model is integrating without any issues though I know that its separate from the main NBM model.

### Expected behavior

NBM data should be integrating

### Actual behavior

NBM data stopped integrating with the last update being 2024-05-13 11Z

### API Endpoint

Production

### Location

Ottawa, Ontario

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
!!! Seeing these errors on my end now as well !!!

**Comment by cloneofghosts** [comment]
I'm guessing the investigation is causing the API to return a Internal Service Error?

**Comment by alexander0042** [comment]
Yea- what's happening is for some strange reason, I'm getting connection reset errors getting data from S3. Usually this isn't too much of an issue, they just repeat. However, the number of errors increased to the point it's not recovering on its own, so writing some error catching code

**Comment by cloneofghosts** [comment]
Was just about to make a comment that prod is back up but you beat me to it. So is this issue something that will sort itself out on its own?

Also seeing the same issue that you fixed this morning where I'm getting a mix of 2.0.5 and 2.0.6.

**Comment by cloneofghosts** [comment]
@alexander0042 Don't know if it's related to this issue or something else but I started seeing `"precipType": -999,` in the currently and minutely sections. The minutely summary and icon are also broken

```
"minutely": {
  "summary": -999,
  "icon": -999,
```

**Comment by alexander0042** [comment]
Ok, isolated the NBM Issue to an ingest file that failed in a way I hadn't thought of. Corrected now and everything seems to be moving correctly now

**Comment by cloneofghosts** [comment]
Yup, NBM seems to be working again though it looks like HRRR_subh seems to have disappeared.

**Comment by alexander0042** [comment]
Win some lose some... fixing it now

**Comment by cloneofghosts** [comment]
I just noticed that HRRR_subh is back so that's been fixed. I'm not sure if NBM is failing to ingest again and will fix itself or if it's stuck like it was earlier.

Seems to be a never-ending cycle at the moment. :laughing:

**Comment by cloneofghosts** [comment]
@alexander0042 NBM seems to have gotten stuck again as the last update was the 15Z run from yesterday.

**Comment by alexander0042** [comment]
Yea, either NOAA or AWS is having issues moving the files over from one side to the other for NBM today. This created a ton of issues with updating, since the data was partially there and I'd assumed it would either all be there or none of it. Regardless, good reason to improve the code, since it gave me a reason to add some additional error checking and NOMADS fallback!

Good news is that the AWS bucket seems to be re-populating now, just as I finished the fallback plan, so it should be updating again shortly, as well as more resilient in the future.

**Comment by cloneofghosts** [comment]
Can confirm that its updating again. I'll leave this open for a day or two to make sure that things are working before closing.

**Comment by cloneofghosts** [comment]
Things seem to be working so I'll close this.
