### ISSUE TITLE
500 Internal Server Error accessing https://api.pirateweather.net/forecast

### ISSUE THREAD

**Issue by Johnnycyan** [Pirate-Weather/pirateweather#232]
### Describe the bug

I set up the integration yesterday, it was running fine. Woke up today and it hadn't updated in 8 hours. So, I restarted my HA and now it just says: "Failed setup, will retry" and then when I hover over that it says 500 error when accessing https://api.pirateweather.net/forecast/

### Expected behavior

It should not error

### Actual behavior

It errors

### Home Assistant version

2024.5.3

### Integration version

1.5.2

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/), [parameter documentation](https://web.archive.org/web/20230128172320/https://www.home-assistant.io/integrations/weather.darksky/) and [sensor documentation](https://web.archive.org/web/20230326100953/https://www.home-assistant.io/integrations/darksky) before opening this issue.
- [X] I have searched this repository and [Pirate Weather Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have checked to see if the issue is not an API issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
Thanks for the report. Since this is an issue with the API I've moved it to the API repo and I'll ping @alexander0042 to look into this.

It only seems to be affecting those locations in the HRRR domain. Like #208 if you add `&exclude=hrrr` to the url you can access the API.

**Comment by Johnnycyan** [comment]
> It only seems to be affecting those locations in the HRRR domain. Like #208 if you add `&exclude=hrrr` to the url you can access the API.

I'm assuming I am not able to add &exclude=hrrr in my HA setup though?

**Comment by Johnnycyan** [comment]
Ah yeah I just edited the `weather_update_coordinator.py` `_get_pw_weather` function to add `+ "&exclude=hrrr"` and it works for now

**Comment by alexander0042** [comment]
Sorry, this was a glitch in the new ingest pipeline that took down the prod server. Shouldn't have happened, and pushed v2.0.8 with an emergency fix to bring it back online and add some more graceful error checking code to make sure it doesn't happen again

**Comment by cloneofghosts** [comment]
Can confirm that everything is working again so will close this issue.
