### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by harrisonpage** [Pirate-Weather/pirateweather#242]
### Describe the issue

As of earlier this afternoon, requests to https://api.pirateweather.net/forecast are returning HTTP 500 errors: "Internal Server Error"

Example usage:

```
curl -v 'https://api.pirateweather.net/forecast/REDACTED/36.5907,-121.942?exclude=minutely'
```

I tried from several machines and even made a new, throwaway account with a different API key to make sure it wasn't limited to my network or my API key.

Thank you for your time!

### Acknowledgements

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
Seems to be the same issue that happened at the end of last month which I reported in #208. 

I'll ping @alexander0042 to take a look at this but for now the workaround in that issue still works

**Comment by harrisonpage** [comment]
Excellent, thanks @cloneofghosts, the workaround does indeed work!

**Comment by cloneofghosts** [comment]
Checked the API this morning and I'm no longer getting this error so will close this issue.
