### ISSUE TITLE
Current Apparent Temperature results inconsistent

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#246]
### Describe the bug

I know this was reported before in #76 and was fixed by using NBM/GFS apparent temperature. While for the most part this fixes the issue I've found that if NBM and HRRR forecast different temperatures then the apparent temperature shown in the API can be off.

This is what I see in the API currently:

```
"currently": {
  "time": 1717703760,
  "summary": "Rain",
  "icon": "rain",
  "nearestStormDistance": 0,
  "nearestStormBearing": 0,
  "precipIntensity": 3.3043,
  "precipProbability": 0.98,
  "precipIntensityError": 1.61,
  "precipType": "rain",
  "temperature": 22,
  "apparentTemperature": 20.45,
  "dewPoint": 20.55,
  "humidity": 0.89,
  "pressure": 986.47,
  "windSpeed": 4.59,
  "windGust": 7.08,
  "windBearing": 259,
  "cloudCover": 0.86,
  "uvIndex": 0.94,
  "visibility": 4.65,
  "ozone": 333.81
},
```

### Expected behavior

The `apparentTemperature` results are inconsistent depending on HRRR and NBM temperatures.

### Actual behavior

The `apparentTemperature` should be consistent no matter what temperatures are returned by the models.

### API Endpoint

Production

### Location

Ottawa, Ontario

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
Thanks for bumping this! Super quick clarification, but what do you mean by "consistent"? Apparent temperate is one of the most irritating parameters, since it's not in HRRR, so only comes from NBM or GFS, which could lead to bigger differences if nbm is excluded or something. However, since regular temperature typically comes from NBM, then it should pretty closely match apparent

**Comment by cloneofghosts** [comment]
I wasn't really sure how exactly to title this issue so I had originally titled this Apparent Temperature results seem off but I changed the title to what it is because I thought it fit better?

I've been having trouble trying to exactly word the issue but because the current data is a mix of NBM and HRRR the apparent temperature displayed may not be entirely accurate whereas the daily and hourly forecast all comes from NBM so everything lines up there.

As an example I put my temperature and humidity into a heat index calculator and got 35C whereas the API is reporting 36.51.

**Comment by alexander0042** [comment]
Ohh, I got ya, for currently! That makes more sense, and is trickier, since you're exactly right, it is a mix of things. Maybe for currently inside the NBM domain it would make sense to calculate humidex/ wind chill manually, like V1 did, and return that. I already have the code written, so would be easy to implement.

I agree we should do something, since they're such closely related parameters, they really should be consistent.
**THIS IS A REMINDER TO ME TO UPDATE THE DATA SOURCES DOC ONCE THIS IS UPDATED**

**Comment by cloneofghosts** [comment]
The wind chill/humidex values could be a separate feels like field or something along those lines. I think the best solution would be to calculate the apparent temperature manually and use that instead? Would also future-proof things for when more models get introduced which may or may not have an apparent temperature field.

**Comment by cloneofghosts** [comment]
As I posted above I think these two things would make the most sense:

1. Calculate the apparent temperature and use it everywhere. It doesn't make sense to have a formula to calculate it just if you're inside the HRRR/NBM domain.
2. Have a new data point (maybe feels like temperature?) for humidex/wind chill and use the formula that you used in V1.

I also noticed this discussion in Breezy Weather where someone calculated apparent temperature which may be helpful here? https://github.com/breezy-weather/breezy-weather/discussions/1085

**Comment by cloneofghosts** [comment]
@alexander0042 Any updates here? I know this isn't the highest of priorities and you're likely working on #229 and #11 but would be nice to get this sorted.

**Comment by cloneofghosts** [comment]
@alexander0042 Any updates here? It's been a while since the last update and am wondering if this will be fixed in the update that you said will be out this week.

**Comment by cloneofghosts** [comment]
Sorry to keep harping on this issue but I'm seeing another instance of the apparent temperature not making sense.
![image](https://github.com/user-attachments/assets/784a5f7b-bcfd-43c9-8f17-f82038963230)

With these conditions I would expect the apparent temperature to be the same or above the current temperature and not below it.

I'm assuming this won't be fixed in the next update as I haven't heard anything on this in over a month.

**Comment by alexander0042** [comment]
Never apologize for following up! I'm writing it up now (along with the surface pressure), and should have it in this week 😃. It's just calculating Feels Like manually for NBM data, using humidex for temperatures > 5 and wind chill below that threshold, so should be nice and consistent

**Comment by cloneofghosts** [comment]
Yeah, I figured the lack of replies was you focusing on fixing the back-end stuff. Isn't the reason why you switched to using NBM Apparent temperature is because you were using humidex/wind chill which wasn't inline with what Dark Sky used? (See #76)

Also unrelated to this but it seems like NBM and GFS have gotten stuck again this afternoon.

**Comment by alexander0042** [comment]
Got this into 2.1! I ended up going with your breezy reference, since it really is clean and simple, and adding in another variable calls "feelsLike" that passes along either the NBM or GFS results. I totally see how the inconsistency with the HRRR data could be weird; however, I want to provide a source for the raw models data as well. This way "apparentTemperature" is the authoritative, Dark Sky one should always be consistent.

**Comment by cloneofghosts** [comment]
Oh nice. Will need to update the docs to reflect the changes (API docs and OpenAPI spec) which can be done on my branch.

So to summarize the changes:

- Apparent temperature is now calculated
- Apparent temperature from the models is now a data point called `feelsLike`
- Wind chill and humidex are not data points

**Comment by cloneofghosts** [comment]
The first few times I tested this the `apparentTemperature` was close to the current temperature but now when I look the `apparentTemperature` is way below the current temperature.  Below is the whole currently block if that helps at all:

```
"currently": {
  "time": 1723661640,
  "summary": "Clear",
  "icon": "clear-day",
  "nearestStormDistance": 101.63,
  "nearestStormBearing": 101,
  "precipIntensity": 0,
  "precipProbability": 0.02,
  "precipIntensityError": 0.02,
  "precipType": "none",
  "temperature": 27.68,
  "apparentTemperature": 20.75,
  "dewPoint": 17.18,
  "humidity": 0.51,
  "pressure": 1007.78,
  "windSpeed": 15.7,
  "windGust": 20.8,
  "windBearing": 310,
  "cloudCover": 0.13,
  "uvIndex": 5.76,
  "visibility": 16.09,
  "ozone": 345.21
},
```
