### ISSUE TITLE
UV Index is some outrageous number, looks like some integer overflow

### ISSUE THREAD

**Issue by nasserakhter** [Pirate-Weather/pirateweather#249]
### Describe the bug

![image](https://github.com/Pirate-Weather/pirateweather/assets/49543791/b03d5096-5b62-47fc-94dd-0f1b7891dc34)

When viewing the data for UV Index at 4:05AM in Elk Grove, CA, USA the number is like something a billion or a trillion.

### Expected behavior

I don't think that high of a UV index is possible, it should just be around 1-20 ish

### Actual behavior

It shows 88123938833852000

### API Endpoint

Production

### Location

Elk Grove, California, United States

### Other details

Viewed via Merry Sky

### Troubleshooting steps

- [x] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
Duplicate of #229
