### ISSUE TITLE
Finding Actual Forecast Location

### ISSUE THREAD

**Issue by pettazz** [Pirate-Weather/pirateweather#25]
Hello, I see in the documentation you mention using a nearest grid cell calculation to find the appropriate forecast based on the lat/lng params passed in on the request. Would it possible to include that in the response? For context, I am looking to use the API to handle requests from potentially any location and would like to add a caching layer between my app and Pirate Weather so that we don't make unnecessary of requests for what's effectively the same location multiple times within a given timeframe. So ideally I'd like to do something similar on my end and cache results for particular areas. ZIP codes are an option but vary in size pretty wildly and of course are only in the US. I could also do some kind of grid calculations on my side and use that but if there is an already available data point, that would be much easier!

**Comment by alexander0042** [comment]
Hi,

Great question, and something that will be really easy to add in! I use a pretty simple approach to determine the closest grid cell, by finding the minimum of the difference between all the lat and longitudinal points, and so the matching point is already calculated internally. I'll see if I can add that in under the flags section later this week, and I'll update here when that happens! 

For your specific application, one thing that might be useful is if I shared the exact code that's calculating a point, that way you could directly check to see if a request will be calling a new point, or if it's a cached one.

**Comment by alexander0042** [comment]
Thanks for following up here! Still on tap, and should be in the next month (for real this time)!

**Comment by cloneofghosts** [comment]
This feature has been added in the V2 development API which you can access using the dev endpoint.
