### ISSUE TITLE
Inconsistent API response (merry & curl vs HA) - always raining

### ISSUE THREAD

**Issue by liquidblack** [Pirate-Weather/pirateweather#251]
### Describe the bug

Pirateweather status is (almost) always raining

Trying to move from openweather to pirateweather with HA - this does not _appear_ to be a HA problem but it's nice and easy to set up a comparison during the transition

Checked the API using curl/merry and the summary is clear, icon "clear-night" in the middle of the day.
Same request via HA brings very slightly different data - but always seems to be raining

![image](https://github.com/Pirate-Weather/pirateweather/assets/8546685/4df7aff7-15ca-4a1c-8afb-4615642feaaa)

### Expected behavior

Expecting the same output from the API for both merry, curl and HA

### Actual behavior

HA always seems to be raining

### API Endpoint

Production

### Location

Ystad, Sweden

### Other details

Turned on debug logging in HA but only got 2 or 3 lines to say "success" fetching data

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by liquidblack** [comment]
Added a couple of json dumps for both merry and curl - very different answers for the same location (edited lat/long to "near" my location)

[merry.json](https://github.com/user-attachments/files/15883458/merry.json)
[curl.json](https://github.com/user-attachments/files/15883459/curl.json)

**Comment by cloneofghosts** [comment]
I wonder if this is related to the weird results people have been reporting recently. (See #229) I checked your location in my browser and it's showing Cloudy at the moment with `"precipIntensity": 0.0197,` (it needs to be 0.02mm/h or higher to show the rain icon)

Maybe this was something that @alexander0042 fixed or maybe like the other issue it's coming and going based on which server you get.

**Comment by cloneofghosts** [comment]
@liquidblack Are you still having this issue? There were some API updates yesterday which should have solved this issue.

**Comment by cloneofghosts** [comment]
Haven't heard anything and it looks like the API updates from a few days ago solved this issue.
