### ISSUE TITLE
Can't sign in to my (old) account

### ISSUE THREAD

**Issue by pketh** [Pirate-Weather/pirateweather#254]
### Describe the issue

Hi, I created my account and API key in 2022. I'd like to sign in to rotate my API key for security reasons. However when I enter my username and password on https://pirate-weather.apiable.io/login the form returns an 'incorrect username or password' error. 

When I click to reset my password, the reset password email never arrives. I've checked my spam folder and everything, but I don't see it. 

### Acknowledgements

- [X] I have searched this repository to see if the issue has already been reported.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
That's great security practice, so frustrating that it's happening! If you're ok posting the e-mail you signed up with here I can take a look at it, otherwise shoot me a message to mail@pirateweather.net

**Comment by pketh** [comment]
ah okay that makes sense, thanks for clearing that up!

**Comment by pketh** [comment]
there's a chance that the old api key is exposed. Are you able to disable it just in case?

**Comment by alexander0042** [comment]
Yup! Ping me here when your new key is created and I'll disable the old one

**Comment by pketh** [comment]
new key created and it seems to be working fine on production, so def feel free to delete the old one thanks

**Comment by alexander0042** [comment]
Great, thanks!
