### ISSUE TITLE
Summary sometimes an Integer

### ISSUE THREAD

**Issue by trevorturk** [Pirate-Weather/pirateweather#264]
### Describe the bug

Just a minor note to say that sometimes in the last couple weeks, I've been seeing summary text coming back as an Integer, not a String. Example location would be 40.2/-75.0. 

### Expected behavior

Summary should be a String.

### Actual behavior

Summary is an Integer. 

### API Endpoint

Production

### Location

40.2/-75.0
40.4/-74.2
42.5/-83.0

### Other details

First instance June 24th, then a gap, then recurring starting July 10th. 

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
While I haven't ran into this myself I will ping @alexander0042 to look into this to see what's going on. Is there a specific data point where this occurs or can it happen anywhere?

**Comment by trevorturk** [comment]
Sorry I didn't look closer before! All of the errors I've seen are on the `minutely->summary` data point.

**Comment by cloneofghosts** [comment]
No worries! In general I find those summaries to be a bit buggy where the summary and the icon don't match up at times but I haven't seen it be an integer before.

**Comment by alexander0042** [comment]
Thanks for catching this! Integer is particularly weird, but credit (I guess) to Python for just rolling with whatever data type a variable happens to end up as. I'll dig into it and put out a fix in the next update!

**Comment by trevorturk** [comment]
No worries. Note I haven't seen another instance for a while, but I'll report back if/when I do. If you don't hear from me by the end of the month, I'd say it's safe to close anyway. Thanks!

**Comment by trevorturk** [comment]
I haven't seen this since, so I'm closing for now. Will reopen if I see it coming back up!
