### ISSUE TITLE
Temperature Anomalies - Apparent Temperature was 178,423°F

### ISSUE THREAD

**Issue by qJake** [Pirate-Weather/pirateweather#266]
### Describe the bug

On multiple occasions recently, the apparent hi/lo temps have been inaccurate by a significant order of magnitude.

![image](https://github.com/user-attachments/assets/048a7909-de9f-4603-be3f-bf25a271b802)

The issue first appeared on 2024-07-11 at 11:35:00 UTC.

### Expected behavior

I expect the weather forecast data to be within a reasonable range.

### Actual behavior

The weather forecast data said that my backyard was 10x hotter than the surface of the sun.

### API Endpoint

Production

### Location

Chicago, IL, US

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by jhemak** [comment]
I have seen this as well

**Comment by cloneofghosts** [comment]
I haven't ran into this myself personally I will ping @alexander0042 to look into this.

**Comment by alexander0042** [comment]
Can you double check if you briefly passed through the [interior of the ITER fusion reactor](https://euro-fusion.org/faq/what-is-the-temperature-generated-in-a-tokamak/)?

In all seriousness, this shouldn't have happened, and has the same root issue as the irregularities from last month. I almost have version 2.1 ready, which will switch to a much more stable back-end database, and should resolve these glitches

**Comment by qJake** [comment]
Can confirm that I have not passed though, in, near, or around any fusion reactors lately. 😎

2.1 sounds exciting - can't wait for that! Although I will miss my morning PA announcement saying "*Today in Chicago, the high is one hundred seventy eight thousand, four hundred and twenty three degrees Farenheit.*" The wife and I had a good chuckle over that one.
