### ISSUE TITLE
Daily high/low temperature calculation issue

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#268]
### Describe the bug

I've noticed that the daily high and low temperatures do not take into account 6pm for the daily high and 6am for the daily low. If the daily high temperature is at 6pm then that temperature isn't shown as the daily high. Same goes for the nightly low if its at 6am then it also isn't used as the daily low temperature.

### Expected behavior

Daily high should include 6pm and daily low should include 6am when calculating the high and low temperatures

### Actual behavior

Daily high does not include 6pm and daily low does not include 6am when calculating the high and low temperatures

### API Endpoint

Production

### Location

Ottawa, Ontario

### Other details

I had posted this comment in #239 a few weeks ago but it looks like it was missed so posting here for better visibility.

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
I thought the daily high/low temperatures would be calculated based on the hour and not based on the minute considering the models only have 1h time-steps.

I think the end time for the daily high/low temperatures just need to be extended by 1h and it should be good. This could lead to a situation where one days low has the same time as the next days high but it seems pretty unlikely.

**Comment by alexander0042** [comment]
You're correct, they are based on the hour- I just used minutes there to be clear which hour was included or not, but might have made it more complicated. Solution makes sense, and I'll put it in.

**Comment by cloneofghosts** [comment]
I noticed that this issue seems to be fixed on 2.0.11 but when I check development version 2.1 it doesn't have the fix. Maybe it was just added to the wrong place?

**Comment by alexander0042** [comment]
Ok, just migrated this fix over to the dev backend, so it'll be live in 2.1!
