### ISSUE TITLE
Why is lumache.py in the repository?

### ISSUE THREAD

**Issue by mbomb007** [Pirate-Weather/pirateweather#276]
### Describe the issue

https://github.com/Pirate-Weather/pirateweather/blob/main/lumache.py

The file doesn't seem to be relevant.

### Acknowledgements

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
This repository was generated from a [Read the Docs tutorial repository](https://github.com/readthedocs/tutorial-template) which includes that file.

I'm not sure if this file is required at all so I'll ping @alexander0042 to see if it can be removed at all.
