### ISSUE TITLE
Pressure has extreme values (like -308024647.68 or 151026579537.92) at some point of the forecast

### ISSUE THREAD

**Issue by tkafka** [Pirate-Weather/pirateweather#283]
### Describe the bug

A pressure runs into extreme positive and negative values (so large that my uint32 encoding fails).
I can see it happening right now (timestamp 1723022370 or `2024-08-07T09:19:30+00:00`)

Request: https://api.pirateweather.net/forecast/<api token>/38.631,-105.071?exclude=currently,minutely,daily,alerts,flags&extend=hourly&units=si&version=2

Also visible on Merry Sky: https://merrysky.net/forecast/38.631,-105.071/ca

<img width="1327" alt="image" src="https://github.com/user-attachments/assets/6c0e3e80-6205-4541-b8d3-4407389f87e9">

### Expected behavior

The pressure should have expected values

### Actual behavior

The pressure have values exceeding uint32 in both positive and negative values at some point in the forecast

### API Endpoint

Production

### Location

38.631,-105.071

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
Am also seeing the same issue this morning. I had checked the development endpoint (which is running 2.1 currently) about an hour ago and was seeing the same issue but when I check now everything is back to normal.

I looked at the two endpoints and the development endpoint has integrated the 06Z GFS run whereas production has not. I bet there is some sort of issue with the 00Z GFS run which the 06Z run doesn't have. From what I can see only the 00Z GFS run gets integrated into production which is something that V2.1 fixes. Will ping @alexander0042 to look into this
