### ISSUE TITLE
Pressure reading jumps to 3000 mbar at midnight

### ISSUE THREAD

**Issue by ligius-** [Pirate-Weather/pirateweather#284]
### Describe the bug

I'm using Home Assistant but there have been no changes that I know of in that area. Since a week or so the pressure value jumps exactly at midnight to 3000 and then it recovers.

![image](https://github.com/user-attachments/assets/5b3b427c-851a-4833-bb03-5e7b5769b26a)

### Expected behavior

Pressure should have a reasonable value.

### Actual behavior

Pressure jumps to 3000 mbar

### API Endpoint

Production

### Location

Timisoara, Romania

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
Thanks for using Pirate Weather and reporting this issue! Definitely a problem, so really needs to be fixed. 

It's related to the ongoing (but fixed soon) bug with respect to data ingest (#266). As it currently stands, values are overwritten on the disk when new results come online; however, every so often a read happens at the same time as a write, and the glitch manifests with these crazy values. 2.1 (live on the dev endpoint) switches to a LMDB backend, which removes all of the ugly disk overwriting stuff, so should address this!
