### ISSUE TITLE
Extreme Wind Forecast

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#294]
Good spot. Mine said 1.5.5 too. If you edit manifest.json in the custom_components folder and change the version to 1.5.6, then reload the integration, it starts ok. 

However, I’m still getting wild forecast data that’s orders of magnitude out. E.g

![Screenshot 2024-08-17 at 12 05 47](https://github.com/user-attachments/assets/ca4520ca-af6b-43e9-93cf-a1a41b2dbadf)

Of course this may be a completely separate issue. Any of you in this thread seeing this issue too?

_Originally posted by @fenty17 in https://github.com/Pirate-Weather/pirate-weather-ha/issues/290#issuecomment-2294828274_

**Comment by cloneofghosts** [comment]
Hi @fenty17 I created this issue for you from your comment. The issue with the `wind_speed` you're seeing is an issue with the API and as a consequence with the 2.1.1 update it also affects apparent temperature as it uses wind speed to calculate so that's why that is also showing extreme values. Will ping @alexander0042 to look at this to see if he can figure anything out.

Just to help with testing whereabouts are you located?

**Comment by fenty17** [comment]
Huge thanks @cloneofghosts for creating the issue! I was going to do so myself but was going to check with the API in browser first and hit a hurdle trying to obtain my API key from my account (undefined). 

No similar issues before this version. I’m located in Shetland Islands UK. 
Lat: 59.931
Long: -1.361

Currently wind speed is showing as many millions of mph!

![Screenshot 2024-08-17 at 18 43 13](https://github.com/user-attachments/assets/5d0126fa-cf8f-4f71-bb45-5dab8c4c2b43)

**Comment by cloneofghosts** [comment]
Thanks for posting your location. I checked the API in my browser and I see the same extreme wind speeds that the HA integration is showing. It's likely related to the recent 2.1 API update that went live a few days ago. Unfortunately there's not a whole lot you can do on your end until it gets fixed.

**Comment by alexander0042** [comment]
Ok, good catch here, and I was quick enough this time to catch it in the act, which really helps with debugging! Investigating now

**Comment by alexander0042** [comment]
While I really thought the LMDB approach would solve this, it apparently did not, and is proving to be trickier than it should be! The good news is that this report let me really hone in on the issue, and I've diagnosed it down a lot. The ingest scripts are working fine, the transfer to the response servers is ok, it's just the saving to the database that's the issue. Something seems to fail silently, and just start writing garbage data instead of the correct values. 

In the short term, I've switched the response servers to restart every 6 hours. This is the nuclear option, and basically just recreates the environment all the time, but should address this for now.

**Comment by fenty17** [comment]
Thanks for the explanation @alexander0042, and I’m sorry for you that this is one of those PITA issues that’s not easy to work out! I can confirm my data is currently ok. If there’s anything else I can do to help let me know. As I said before, no issues whatsoever until this latest release so it’s presumably down to a recent change.

**Comment by cloneofghosts** [comment]
> While I really thought the LMDB approach would solve this, it apparently did not, and is proving to be trickier than it should be! The good news is that this report let me really hone in on the issue, and I've diagnosed it down a lot. The ingest scripts are working fine, the transfer to the response servers is ok, it's just the saving to the database that's the issue. Something seems to fail silently, and just start writing garbage data instead of the correct values.

What I've noticed is that the only models which seem to have trouble integrating new runs is NBM (including NBM fire) and GFS. I remember when I was testing the 2.1 update on the development endpoint everything was working fine so not sure what changed since then. I was going to check the dev endpoint to see if its having the same issue but I'm getting an error trying to visit.

**Comment by fenty17** [comment]
Testing endpoint has been down for a few days by the seems of things - [https://pirateweather.xitoring.io/](https://pirateweather.xitoring.io/)

**Comment by cloneofghosts** [comment]
Yeah, it has been. Wonder if its to prepare to open source the code? Either way since the extreme wind speeds has been fixed I'll code this issue. If it pops up again feel free to comment and we can re-open this issue.
