### ISSUE TITLE
NBM and GFS models integrate once a day

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#297]
### Describe the bug

This was an issue with V2.0.11 and was fixed in V2.1 on the development endpoint but when V2.1 was made live these models initially never updated. With the 6h restart policy added in #294 its now back to updating once per day.

When initially looking at #293 I was able to test on the development endpoint and it was broken there as well. With the recent updates the development endpoint is down and has been for a few days.

### Expected behavior

NBM should be updated every hour, NBM Fire and GFS updated every six hours

### Actual behavior

NBM, NBM Fire and GFS update once a day

### API Endpoint

Production

### Location

Ottawa, Ontario

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
@alexander0042 I noticed that NBM and GFS have integrated a new run but now HRRR sub-hourly is missing. Not sure if you're working on this or if something else is happening.

**Comment by alexander0042** [comment]
You beat me to the 2.2 docs that addresses this! I want to watch it for a couple days, but really think this approach will work. As additional upsides, it's simpler for self-hosting (going back to straightforward directories) and faster (~10 ms for everything to run)

**Comment by cloneofghosts** [comment]
I'll leave this issue open and let you update the PR and merge it in when its ready to launch.

I'm also seeing a mix of 2.2 and 2.2a depending on which node I hit.
