### ISSUE TITLE
Cannot retrieve API key

### ISSUE THREAD

**Issue by rotherpawel** [Pirate-Weather/pirateweather#303]
### Describe the issue

When I try to unhide tha API key on https://pirate-weather.apiable.io/subscriptions/{my_subscribcion}/Details, there is visible "Retrieving..." info in API key field, then after a while there is visible random text like: "The first website was published in 1991.". When I try to regenerate API key it behave the same, after a while I see a random text.

I also create a new account and when I try to get new subscribtion there is visible an error: 
`{
    "timestamp": "2024-08-22T08:23:46.242+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "message": "Failed to parse HTTP response: unexpected EOF",
    "path": "/api/int/subscriptions"
}`

### Acknowledgements

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
Really sorry for this! Bug in a config file took down both production backends. It's fixed now, so should be working again
