### ISSUE TITLE
Support putting the API key in the request header, rather than the URL.

### ISSUE THREAD

**Issue by mbomb007** [Pirate-Weather/pirateweather#314]
### Describe the feature

The documentation says to keep the API key secret. However, requiring the API key to be in the URL makes that difficult, as request URLs show up frequently in logs and error messages, which risks exposure of the API key in various places. Ideally, you would accept a header like

```
api-key: 1234567890
```

If this is already supported in some way, it should be documented.

### Acknowledgements

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the feature has already been requested.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
Thank you so much for opening this! It's a great point, and actually is already a thing (credit to Kong), and will be added to the V2.3 documentation. They keyword here is `apikey`, passing that with a value of your Apiable key should work so long as there's some alphanumeric text in the URL where they key would be. Not sure anyone would ever use it, but it also works as a url query parameter: `apikey=...`.

**Comment by alexander0042** [comment]
Sorry, should have been more clear. It still needs something there for path matching to work, but isn't used. So the syntax is:

'''
https://api.pirateweather.net/forecast/{anythingAtAll}/{lat},{lon}
'''

And then the 'apikey' header/ value combo. Maybe "KeyInHeader" would be a nice string to put there to make troubleshooting easier, but honestly doesn't matter at all.
