### ISSUE TITLE
Documentation doesn't describe error responses.

### ISSUE THREAD

**Issue by mbomb007** [Pirate-Weather/pirateweather#315]
### Describe the issue

I see an example response for a success (200), however, I don't see any examples for 401 (authentication needed), or for any bad request or rate limit exceeded responses. It would be helpful for developers to know what response code and response is sent in those cases.

Also, Dark Sky had a header in the response `X-FORECAST-API-CALLS` that indicated the number of requests sent so far for the current limit period (month). Is there such a thing for the current API?

### Documentation URL

https://docs.pirateweather.net/en/latest/Specification/

### Acknowledgements

- [X] I have searched this repository to see if the issue has already been reported.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
> Also, Dark Sky had a header in the response that indicated the number of requests remaining for the current limit period (month). Is there such a thing for the current API?

These response headers exist to show you your requests limit, number remaining and the time in seconds on when it will reset.

```
ratelimit-limit: 25000
ratelimit-remaining: 24680
ratelimit-reset: 2264045
```

This should probably be added somewhere to the documentation. Dark Sky does have a [response headers](https://web.archive.org/web/20191203113427/https://darksky.net/dev/docs#response-headers) section which can easily be added to the docs.

I looked at the Dark Sky docs and they also don't mention any error messages so maybe it could be added to a section? @alexander0042 What do you think?

**Comment by cloneofghosts** [comment]
I haven't hit the limit myself but there are comments in the HA repo which seem to suggest that you get a 429 error when you've run out of requests [here](https://github.com/Pirate-Weather/pirate-weather-ha/issues/221#issuecomment-2252027016) and [here](https://github.com/Pirate-Weather/pirate-weather-ha/issues/230#issuecomment-2176052062)

**Comment by cloneofghosts** [comment]
Just did some testing and found these error codes:

Invalid API Key/Key not authorized for an endpoint - 401 error
If you put in an invalid route such as https://api.pirateweather.net/asd/ or supply no lat and long - 404
If you use characters for lat/long such as https://api.pirateweather.net/forecast/API/x,x or if you supply only a longitude or only a latidude - Body shows status code 400 return code is 200
Invalid lat/long such as 200,200 - Internal Server Error 500 error code

If there's anything else you want me to test lmk but I think that covers most things. A few bugs to be ironed out such as the Invalid Location Specification returning a 200 status and lat/long outside of -180 to 180 returning an Internal Server Error

**Comment by alexander0042** [comment]
These are great points! I'm going to get those error codes cleaned up as a starting point, since they should be working, but broke in the Lambda to Kong transition and never got fixed

**Comment by cloneofghosts** [comment]
@alexander0042 Thinking about this a bit but maybe the error code responses should be added to the OpenAPI spec? I took a look at how its setup and it should be possible to setup.

**Comment by cloneofghosts** [comment]
Added the error codes and the response to the OpenAPI spec. I couldn't figure out how to create line breaks in the example so there's a few HTML responses which I was unable to put on two lines.

**Comment by cloneofghosts** [comment]
The documentation/OpenAPI spec has been updated to add response headers and error codes so I'll close this issue.

The `X-FORECAST-API-CALLS` request seems to have been missed so if you want you can create a new issue using the enhancement template

**Comment by cloneofghosts** [comment]
Sounds good. I created an issue anyways since there are other response headers Dark Sky had which PW doesn't.
