### ISSUE TITLE
Internal Server when using coordinates outside the maximum longitude/latitude 

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#318]
### Describe the bug

As noted [here](https://github.com/Pirate-Weather/pirateweather/issues/315#issuecomment-2330206714) if you use coordinates which contain values outside the maximum longitude or latitude the API returns an Internal Server Error instead of 400 Bad request

### Expected behavior

The API returns an Internal Server Error

### Actual behavior

The API should return 400 Bad Request Error instead

### API Endpoint

Production

### Location

91,181

### Other details

If you query the API using characters instead of numbers it returns 400 Bad Request (such as using x,x)

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
Great idea here,, and fixed in 2.3! There's specific error handling for latitude/ longitudes that are not valid (out of range), as well as a catch all for things like text characters and whanot.
