### ISSUE TITLE
Update references to `precipitationIntensity`

### ISSUE THREAD

**Issue by mbomb007** [Pirate-Weather/pirateweather#328]
### Describe the issue

> precipIntensityError
> The standard deviation of the `precipitationIntensity` from the GEFS model.
> precipIntensityMax
> Only on daily. The maximum value of `precipitationIntensity` for the given day.
> 
> precipIntensityMaxTime
> Only on daily. The point in which the maximum `precipitationIntensity` occurs represented in UNIX time.
> 
> precipIntensityMin
> Only on daily. The minimum value of `precipitationIntensity` for the given day.
> 
> precipIntensityMinTime
> Only on daily. The point in which the minimum `precipitationIntensity` occurs represented in UNIX time.

This (and any other references) should be updated to say `precipIntensity` instead of `precipitationIntensity`, matching the actual property/field name.

### Documentation URL

https://docs.pirateweather.net/en/latest/API/

### Acknowledgements

- [X] I have searched this repository to see if the issue has already been reported.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
I must have accidentally used `precipitationIntensity` instead of `precipIntensity`. I should be able to update the documentation to fix this later today but you're always free to submit a PR to fix this issue or other documentation issues you notice :smile:
