### ISSUE TITLE
API sometimes returning extreme values

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#332]
### Describe the bug

Noticed this morning that the API sometimes is returning really extreme values for certain data points like `apparentTemperature`, `humidity` and `temperature`.

I also noticed that the currently and minutely data has `precipProbability` returning -999 and `visibility` is always returning 0.

![image](https://github.com/user-attachments/assets/84a7d101-2875-48be-abf7-51c8c867b359)

### Expected behavior

API should not return extreme values

### Actual behavior

API is returning extreme values

### API Endpoint

Production

### Location

Barrhaven, Ontario

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
@alexander0042 I think this might be fixed now? I wonder if the cause was bad data being integrated into one of the servers which is why it didn't happen all of the time?

**Comment by alexander0042** [comment]
Sorry about this! It was a glitch in the healthcheck that kept restarting things, but all better now.
