### ISSUE TITLE
`RateLimit-Reset` header returns wrong value

### ISSUE THREAD

**Issue by mbomb007** [Pirate-Weather/pirateweather#333]
### Describe the bug

When I get the value of the `RateLimit-Reset` header in the API response, it returned `1217931`. It's supposed to return the Unix timestamp, and this would be the timestamp for 1/14/1970 - 8:20 pm...

### Expected behavior

Return the Unix timestamp in UTC for the date the rate limit resets.

### Actual behavior

Returns a number far too small.

### API Endpoint

Production

### Location

N/A

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
Thanks for the report. The documentation states that Ratelimit-Reset is the time in seconds until your rate limit resets.

It should be possible to change it to a UNIX Timestamp but I'll leave it up to @alexander0042 to decide
