### ISSUE TITLE
Return short alert title in alert data.

### ISSUE THREAD

**Issue by mbomb007** [Pirate-Weather/pirateweather#344]
### Describe the feature

I'm fairly certain that Dark Sky had a shorter alert title. Currently, the alert title looks like this:

```
Red Flag Warning issued September 30 at 12:00AM PDT until September 30 at 6:00PM PDT by NWS City State
```

I really think the title should be just `Red Flag Warning`. The NWS .cab (XML) file has this short format in the `<event>` tag, whereas the `title` you are currently using is from the `<headline>` tag. I think the headline and title could both be included in the result. The current title is very long, and is not conducive to showing to the user. It also contains other pieces of data that are separate in the XML, such as `<onset>` or `<effective>`, `<expires>`, and `<senderName>`. This data could also be included in your API response, as separate keys/values.

Otherwise, if I want the shorter title, I will have to parse this long headline.

Also, in the `regions` list, most of the regions contain a leading space. Perhaps the regions in the response should be "trimmed" of whitespace?

### Acknowledgements

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the feature has already been requested.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
> I'm fairly certain that Dark Sky had a shorter alert title.

Taking a look at an [archived version of their documentation](https://web.archive.org/web/20191203113427/https://darksky.net/dev/docs#forecast-request) the example they give has a shorter alert title than what PW gives.

> Also, in the `regions` list, most of the regions contain a leading space. Perhaps the regions in the response should be "trimmed" of whitespace?

Should just be a case of using the Python trim function to remove any extra whitespace. Will ping @alexander0042 to look into this for you.

**Comment by alexander0042** [comment]
Good catch here- alert parsing is so trickier than it should be, so I appreciate feedback like this! I agree with @mbomb007, the current implementation is probably longer than makes sense for a title. Since it's a location based request, the user knows where it's valid for, and the issuing time is included elsewhere. I'll put those changes in for the next update, along with the whitespace catch.

**Comment by cloneofghosts** [comment]
Done in V2.3.2 which is rolling out now.
