### ISSUE TITLE
Local cache issue

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#350]
### Describe the issue

I've noticed a few times in Breezy Weather where the automatic refresh would show data from the previous refresh. I noticed today that when I query the API in my browser that unless I refresh the page after the call I would get cached data from the first time I queried the API no matter how long it's been since the query.

I think this is because the Cache-Control header is missing the [must-revalidate response directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#must-revalidate) .

### Acknowledgements

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
Thanks for flagging this, especially since you found the exact fix! I'll add that directive in and we can see if it fixes it

**Comment by cloneofghosts** [comment]
@alexander0042 Any update here? I saw you commented but haven't seen any change to the Cache-Control header on dev or live.

It only seems to affect querying the API in my browser and occasionally Breezy Weather so is not a urgent issue to fix if you're busy.

**Comment by cloneofghosts** [comment]
Just pinging here to see if there's any update here @alexander0042. I saw you comment two days ago but haven't seen any changes to the Cache-Control header on live or dev.

**Comment by cloneofghosts** [comment]
Still am running into this issue. With Breezy Weather sometimes it takes a few hours for it to grab updated data even though I have the refresh interval set to 30m.

**Comment by alexander0042** [comment]
Thanks for adding the urgent label! This one is live at the dev backend as 2.3.3, so fingers crossed it fixes it

**Comment by cloneofghosts** [comment]
I usually add the tag to stuff we're waiting for a reply from you on and it's been a while (usually a few weeks). I will let you know if that fixes the issue.

Is the next version 2.3.3 or 2.4? I saw the version change to 2.4 briefly and now we're on 2.3.3.

**Comment by alexander0042** [comment]
Haha, I can't get anything by you! I briefly had it set to 2.4 to make the version flag work; however, it's a minor enough update so I think 2.3.3 makes more sense.

**Comment by cloneofghosts** [comment]
Sounds good. I had changed the milestones but changed them back after it was updated to 2.3.3. I also created a draft PR so the docs can be updated. :)

**Comment by cloneofghosts** [comment]
@alexander0042 I just noticed that the max-age is set to 3600 seconds which is 1 hour. If you want it to be 15 minutes it should be set to 900.
