### ISSUE TITLE
Apparent temperature calculation incorrect

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#363]
### Describe the bug

Was looking through the code yesterday to see if relative humidity was capped at 100% (see #360) I noticed that the apparent temperature formula you have is slightly incorrect.

Basically you either need to separate out the formula for calculating water vapor pressure or add brackets around it and should be setup as below:

`AT = Ta + 0.33 × (rh / 100 × 6.105 × exp(17.27 × Ta / (237.7 + Ta))) − 0.70 × ws − 4.00`

How its setup now I believe it leads to the apparent temperature being lower than it should be but cannot confirm.

### Expected behavior

Apparent temperature calculation has brackets around the water vapor pressure formula

### Actual behavior

Apparent temperature calculation is missing brackets around the water vapor pressure formula

### API Endpoint

Production

### Location

Not applicable

### Other details

@alexander0042 This is a good case for the source code to be available. I know you want to try an optimise it more but you could always release as is and add it afterwards? Not sure what the plan is for that as I haven't seen an updated timeline anywhere.

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
@alexander0042 I did a quick apparent temperature calculation using the formula using these values:

```
"temperature": 20.2,
"dewPoint": 16.37,
"humidity": 0.75,
"windSpeed": 5.83,
```

When I did the calculations myself I get 17.674814263 but the API is returning 12.5 which is a more than 5 degree difference.

**Comment by alexander0042** [comment]
Fix for this is live in 2.4.0! Thanks again both finding the bug and the solution, it really is the dream combo!

**Comment by cloneofghosts** [comment]
Comparing both endpoints I see the same apparent temperature. When I plug in the formula in my calculator I get different results still compared to the API.

**Comment by alexander0042** [comment]
Yea, I see that, and my calculator is also showing a difference. Something else must be off here, I’ll have to dig into the formula to see where things go off the rails

**Comment by cloneofghosts** [comment]
I wonder if its something to do with the wind speed or temperature? Might have to do some log statements to see what is exactly going on.

**Comment by cloneofghosts** [comment]
Did this only affect the `currently` block or was it an issue everywhere? The `hourly` block looks to be the same as before.
