### ISSUE TITLE
Weather alert new lines added in middle of sentences

### ISSUE THREAD

**Issue by mbomb007** [Pirate-Weather/pirateweather#367]
### Describe the bug

Newlines were recently added to weather alerts. They are added in the middle of sentences where they shouldn't be.

### Expected behavior

I expect the text to have each section separated by newlines, but not wrap early.

```
"* WHAT...Visibility Below One Half Mile In Dense Fog.

* WHERE...Portions Of Northwest And West Central Iowa, Southwest Minnesota, And Central, East Central, South Central, And Southeast South Dakota.

* WHEN...Until 10 AM CST This Morning.

* IMPACTS...Low Visibility Could Make Driving Conditions Hazardous."
```

`Southwest Minnesota ... Southeast South Dakota`

### Actual behavior

Example:

```
"* WHAT...Visibility Below One Half Mile In Dense Fog.

* WHERE...Portions Of Northwest And West Central Iowa, Southwest
Minnesota, And Central, East Central, South Central, And Southeast
South Dakota.

* WHEN...Until 10 AM CST This Morning.

* IMPACTS...Low Visibility Could Make Driving Conditions Hazardous."
```

`Southwest \n Minnesota ... Southeast \n South Dakota`

It's like the text is wrapped at a certain column, but since websites are dynamically sized, this wouldn't look good if I replaced the newlines with `<br>`, because the lines would be in the wrong place.

### API Endpoint

Production

### Location

Sioux Falls, SD

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
I took a look at the [NWS alert page](https://alerts.weather.gov/search?id=urn%3Aoid%3A2.49.0.1.840.0.720286f2c66fb91185acb3049e4d39b8e317931c.001.1) and the .cap file and the weird line breaks are coming directly from NWS.

I will still ping @alexander0042 to take a look and see if its possible for the API to manually add in the line breaks.

**Comment by alexander0042** [comment]
Checking this morning, I'm seeing formatting like this:
```
"* WHAT...Northwest winds 20 to 30 mph with gusts up to 55 mph\nexpected.\n\n* WHERE...Rapid City.\n\n* WHEN...From 5 AM early this morning to 5 PM MST Wednesday.\n\n* IMPACTS...Sudden wind gusts can cause drivers to lose control,\nespecially in lightweight or high profile vehicles. Strong winds\ncan cause blowing dust, reduced visibility, and flying debris."
```

Which is a good example here, since there's two `\n` in between sections, but one in between chunks. So from this, I think the formatting logic should be:

- `\n` -> `space`
- `\n\n` -> `\n`

I'm going to edit the ingest script and we can see how it looks
