### ISSUE TITLE
Hourly windBearing can be less than 0

### ISSUE THREAD

**Issue by trevorturk** [Pirate-Weather/pirateweather#368]
### Describe the bug

Hourly windBearing can be less than 0

### Expected behavior

Hourly windBearing should be between 0-360

### Actual behavior

windBearing = -18.0 for 41.883,-87.632 at 2024-11-08 19:00:00 -0600

### API Endpoint

Production

### Location

41.883,-87.632

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
Looks like `windBearing` doesn't keep its value between 0 and 360 degrees. The fix is to just use modulo 360 to keep the values between 0 and 360. Will ping @alexander0042 to fix this in the API but for the time being you can add this on your end.

**Comment by alexander0042** [comment]
Sorry I didn't reply to this, was caught up getting the self hosting/ open-source stuff together (so next time I'll be able to point to the exact line where the bug is!). I've added that mod statement in for both the hourly/daily and currently blocks, so should be fixed in 2.4!

**Comment by trevorturk** [comment]
🥇 thank you!
