### ISSUE TITLE
Extreme temperature 

### ISSUE THREAD

**Issue by Generalnoob** [Pirate-Weather/pirateweather#373]
### Describe the bug

Apparently Monday will be cold.. very cold.. 
![17313959146674546069463974529600](https://github.com/user-attachments/assets/04388e75-47ab-4594-ae90-cc7a8821f6a2)

### Expected behavior

Correct temperature 

### Actual behavior

Incorrect temperature (I really hope) if not I ain't going outside 

### API Endpoint

Production

### Location

Finland

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

**Comment by FunctionalHacker** [comment]
Same thing here, Finland too. Since yesterday the temperature has been around 5 degrees Celsius too high.

[Merry Sky](https://merrysky.net/forecast/Saimaanharju/si)
[wttr](https://wttr.in/saimaanharju)

The wttr​ temperature is more close to the real conditions as far as I can tell.

**Comment by Generalnoob** [comment]
> Same thing here, Finland too. Since yesterday the temperature has been around 5 degrees Celsius too high.
> 
> [Merry Sky](https://merrysky.net/forecast/Saimaanharju/si) [wttr](https://wttr.in/saimaanharju)
> 
> The wttr​ temperature is more close to the real conditions as far as I can tell.

For me there is only a .5 degree discrepancy in the current weather  temp compared to my cheapo external thermometer but that's within the tolerance level, the issue is -273c on Monday 🤣😂 love the integration btw when you read these comments Mr dev man ☺️

**Comment by alexander0042** [comment]
Ok, found the root cause here (bug in the ingest script from the self hosting stuff), fixing it now!

**Comment by cloneofghosts** [comment]
Was going to post that I was seeing some issues with the data points on Tuesday but it looks like you found the issue and are solving it.

When I was checking a few locations this morning I noticed that there were a few instances of `cloudCover` being over 100%. That should probably be fixed and other data points should be checked for the same issue. (I know humidity is one as per #360)

**Comment by Generalnoob** [comment]
Great to hear that you found the issue :) sorry I didn't reply quick enough

**Comment by cloneofghosts** [comment]
I noticed that the issue I'm seeing with the data points has been fixed. Can you check to see if the temperatures are back to normal now?

**Comment by Generalnoob** [comment]
> I noticed that the issue I'm seeing with the data points has been fixed. Can you check to see if the temperatures are back to normal now?

![Screenshot_2024-11-12-18-25-56-47_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/6773ec3b-250e-4807-8585-accc6634d5f1)
Looks like it's working again ☺️ thanks for the speedy work
