### ISSUE TITLE
feature missing that was in darksky API  - Weather Now/Weather in 1 Hour/Weather in 2 Hours/Weather in 3 Hours 

### ISSUE THREAD

**Issue by Vitalsignser** [Pirate-Weather/pirateweather#389]
### Describe the feature

For smarthome integration - It would be nice to be able to create an alert about weather in 1hr, 2hrs, 3hrs. For example - family room window is open but it will rain in 1 hr. Polling every 30 min will pick up the change in state of variable and a push notification could be sent thru the HA software. Darksky API had this.  

Weather Now/Weather in 1 Hour/Weather in 2 Hours/Weather in 3 Hours
 These values be one of the following: clear-day, clear-night, rain, snow, sleet, wind, fog, cloudy, partly-cloudy-day, or partly-cloudy-night

### Acknowledgements

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the feature has already been requested.
- [X] I have written an informative title.

**Comment by Vitalsignser** [comment]
actually - it might already be there. Sorry...I will test and get back to you

**Comment by Vitalsignser** [comment]
nevermind...it's all there. Thanks for making this API

**Comment by alexander0042** [comment]
Happy that you tracked down the data you were looking for here- always a throwback to hear from someone who remembers Dark Sky, and happy that the compatibility layer is still useful!

Feel free to open a new issue if anything else comes up
