### ISSUE TITLE
How does The time machine work

### ISSUE THREAD

**Issue by henryeticom** [Pirate-Weather/pirateweather#63]
I wanted to ask how the timemachine api endpoint works. Like for example is the data from yesterday 11th of may 2023 available? also why does it return error if i do not specify any time

**Comment by henryeticom** [comment]
Using DarkSky the Hourly returns 24hrs instead of 48hrs, is it possible this can be looked at as mentioned here: https://github.com/alexander0042/pirateweather/issues/39#issue-1643911389

**Comment by cloneofghosts** [comment]
It's a little bit confusing but there's two separate endpoints for Time Machine data

* The monthly ERA5 dataset which has the same format as the DarkSky Time Machine which you can access using the timemachine URL
* The last five days data which uses the API endpoint which is just saved model data and is where you are likely seeing this issue

The second point might be fixed when he is fixing the daily high/low issue but I'll mention him here so maybe he can take a look @alexander0042
