### ISSUE TITLE
Including a location ID

### ISSUE THREAD

**Issue by ion1** [Pirate-Weather/pirateweather#80]
If I have understood correctly, any request with coordinates within a certain area will receive an identical response. It might be nice if the response included an ID specific to that area.

A service with multiple users having nearby coordinates could then detect that two or more locations map to the same area ID and cache that fact for a period of time. That could be used to avoid duplicate requests for the same area.

Thank you for taking this into consideration!

**Comment by alexander0042** [comment]
This is a great idea, and something I have in progress! It's a little bit more complicated to implement than I thought it would be, but is absolutely in the works. 

My basic idea here is two fold. The first part will be to return the lat/lon of the grid cell that's returned for each (HRRR/GFS) model, which will let people know exactly where the data is coming from. The second phase will be to create a 5 digit geohash from requested lat/long, giving me an accuracy of about 2.4 km (<https://en.wikipedia.org/wiki/Geohash#Digits_and_precision_in_km>). I'm using Kong as my API gateway, so if I can implement this has in the lua scripting language, then this will work as a caching approach

**Comment by ion1** [comment]
Sounds great. The lat/lon of the grid cell would be enough for my purposes.

**Comment by alexander0042** [comment]
Reopened and tagged this as it's definitely on my plan for the next release! It'll just be the lat/lon, but will be returned

**Comment by cloneofghosts** [comment]
This feature has been added in the V2 development API which you can access using the dev endpoint.
