### ISSUE TITLE
Incorrect daily temperatureHigh

### ISSUE THREAD

**Issue by Monstergerm** [Pirate-Weather/pirateweather#85]
This issue has been reported before as #23 (now being closed) but it is still not fixed. There's a bug with the High temperature for the current day after 6pm where it's using the highest forecasted temperature for the week rather than for the current day. 

This affects daily_0 temperatureHigh but not daily_0 temperatureMax.

There is also an anomaly compared to other weather services which was reported previously as #5. The high temperature for the day should be the highest temperature forecasted and/or observed, even it it’s in the past. Currently it turns into the current temperature after the High has been reached.

**Comment by dustinbolton** [comment]
Perhaps the daily temperatureHigh being replaced with the weekly max temp after 6pm is a really easy fix in the meantime? Just thought I'd ask in case 😁

**Comment by RollingStar** [comment]
Not sure I have the right issue thread, but here's a graph from homeassistant demonstrating the gap between "daytime high" and the actual temperatures observed throughout the day/night. 
![image](https://github.com/Pirate-Weather/pirateweather/assets/4810902/0fea0346-3f90-4771-866c-7831be1f1641)

**Comment by cloneofghosts** [comment]
With V2.0c released today this has been fixed.

**Comment by bbrendon** [comment]
Any idea when the fix will appear in Home Assistant?

**Comment by cloneofghosts** [comment]
I don't think there's any firm timeline on when the changes will be pushed up to production probably within a couple of months? @alexander0042 would have a better timeframe on when the approximate launch date is.

I did release a beta version of the Home Assistant integration based on the latest version which uses the development API. The development API does sometimes have downtime so if I wouldn't recommend using the beta version if you're depending on the integration for automations or other things.
