### ISSUE TITLE
UV index values

### ISSUE THREAD

**Issue by smvarela** [Pirate-Weather/pirateweather#88]
Hello, I'm not sure if this is a bug or if different services calculate the UV index using different methods. However, PirateWeather API returns a lower UV index than other weather services.

For example, here are different services reporting the UV index for the same location at the same time. In the table below, I have listed the maximum UV index for the day as reported by each service.

**_Location: Barcelona (Europe) :: lat=42.38563 lon=-2.158
Time 19 July 2023_**

|Barcelona, Spain | |
|---------------------------|----------|
| Service                   | UV Index |
| Pirateweather (merrysky.net) | 8.29     |
| weatheronline.co.uk       | 9        |
| temis.nl                  | 9.7      |
| weather.com               | 9        |
| [spotwx.com](https://spotwx.com/)   | 9.1      |
| theweathernetwork.com/    | 10       |

https://www.weatheronline.co.uk/Spain/Barcelona/UVindex.htm
https://www.temis.nl/uvradiation/nrt/uvindex.php?lon=-2.158&lat=42.38563
https://weather.com/weather/hourbyhour/l/0ce8d487db0a25631ee2017ddbe068bfba0de2b24de23f0b82c95863724f3a86
https://spotwx.com/products/grib_index.php?model=gfs_uv&lat=42.38563&lon=-2.158
https://www.theweathernetwork.com/en/city/es/catalunya/barcelona/uv

**_Location: Denver (Colorado, USA) :: lat=39.75003 lon= -104.9719
Time 19 July 2023_**

|Denver, CO, USA| |
|-------------------------------|----------|
| Service                        | UV Index |
| Pirateweather (merrysky.net) | 7.56     |
| weatheronline.co.uk           | 9        |
| temis.nl                      | 11.3     |
| weather.com                   | 9        |
| [spotwx.com](https://spotwx.com/)   | 9.2      |
| theweathernetwork.com/        | 10       |

https://www.weatheronline.co.uk/Colorado/Denver/UVindex.htm
https://www.theweathernetwork.com/en/city/us/colorado/denver/uv
https://spotwx.com/products/grib_index.php?model=gfs_uv&lat=39.75003&lon=-104.9719

**Comment by alexander0042** [comment]
Thanks for opening an issue- you're definitely in the right place.
UV index is kind of a tricky parameter. It's the only one that comes from a different model, so the processing flow is different. That being said, it should broadly align with the other sources, so these differences do seem weird.

Do you mind checking what you're seeing in PW vs [SpotWX](https://spotwx.com/)? It's another site that displays the raw model results, so Pirate Weather should match 1:1 with what it's showing for UV

**Comment by smvarela** [comment]
Hello, these are the values that i am currently seeing in http://merrysky.net and http://spotwx.com . 

### **_Location: Barcelona (Europe) - Time 19 July 2023_**
https://spotwx.com/products/grib_index.php?model=gfs_uv&lat=41.38804&lon=2.17001&tz=Europe/Madrid&label=Barcelona,%20Catalu%C3%B1a

![spotwx-gfx-barcelona](https://github.com/alexander0042/pirateweather/assets/10855160/fade37c5-8c94-4ce4-8889-210ca978986a)


https://merrysky.net/forecast/barcelona/si


![merrysky-barcelona](https://github.com/alexander0042/pirateweather/assets/10855160/049de964-38d8-4195-a87f-a0bc58de82b7)



###**_ Location: Denver (Colorado, USA) Time 19 July 2023_**
https://spotwx.com/products/grib_index.php?model=gfs_uv&lat=39.74001&lon=-104.99202&tz=America/Denver&label=Denver,%20Colorado

![spotwx-gfx-denver](https://github.com/alexander0042/pirateweather/assets/10855160/5cf0fc45-0f2b-4e2a-8b11-65cabc937e8b)


https://merrysky.net/forecast/denver/si


![merrysky-denver](https://github.com/alexander0042/pirateweather/assets/10855160/86d0de2c-6bdd-4b69-a3c2-0d19fba564ce)

**Comment by cloneofghosts** [comment]
Been using the V2 development endpoint and I've noticed that the UV index actually seems higher when compared to other sites. Most sites have the current UV at 3 or 4 whereas PW (both dev and prod APIs) are reporting a UV of 5.

The V2 development API is slightly lower than the production API but not by much. I assume much hasn't changed here when it comes to the development API?

**Comment by alexander0042** [comment]
Have you noticed any other issues with this? I do notice that it varies from SpotWX; however, it seems to be pretty consistent with other sources. There was a very significant change in UV calculation approach between V1 and V2, so should have been fixed as part of that; however, it is possible that something else is off here

**Comment by cloneofghosts** [comment]
For the most part the UV Index seems fairly similar to what other sites are showing. There are times where the UV Index from PW is higher than other sites and times where its lower but it's hard to tell as it seems like every site says something different.

One thing I noticed is the first night hour usually has a very small UV Index value (<0.1) but I'm not sure if that's a bug or not.
